version: "3.8"

services:

  flask:
    build: ./flask
    restart: always
    expose:
      - "5555"

  nginx:
    depends_on:
      - flask
    build: ./nginx
    restart: always
    ports:
      - "80:8080"
      - "443:44443"
    volumes: 
     - ./flask/src/templates:/var/www/html
     - ./certbot/conf/:/etc/nginx/ssl/
       #   certbot:
       #     depends_on:
       #       - nginx
       #     image: certbot/certbot:latest
       #     volumes:
       #       - ./certbot/www/:/var/www/certbot/
       #       - ./flask/src/templates:/var/www/html
       #       - ./certbot/conf/:/etc/letsencrypt/
       #     command: certonly --webroot --webroot-path=/var/www/html --email AkiyamaSS@yandex.ru --agree-tos --no-eff-email -d xn-----6kc7awhbxbfs.xn--p1ai

