version: "3.3"

services:

  flask:
    build: ./flask
    container_name: Flask-app
    restart: always
    expose:
      - "5555"

  nginx:
    build: ./nginx
    container_name: nginx-server
    restart: always
    ports:
      - "80:8080"
      - "443:44443"
#    volumes: 
#     - ./certbot/www:/var/www/certbot/:ro
#  certbot:
#    image: certbot/certbot:latest
#    volumes:
#      - ./certbot/www/:/var/www/certbot/:rw