version: "3.8"

services:
  nato:
    image: akiyamov/nato-site
    restart: always
    expose:
      - "5555"
  ugol:
    image: akiyamov/ugol-site
    restart: always
    ports:
      - "5050:5050"
  matrix:
    image: matrixdotorg/synapse
    restart: always
    ports:
      - 8008:8008
    volumes:
      - /var/docker_data/matrix:/data
      - /home/ubuntu/nato-site/html:/var/www/html
  nginx:
    depends_on:
      - nato
      - ugol
    image: akiyamov/nginx-sites
    restart: always
    ports:
      - "80:8080"
      - "443:44443"
    volumes:
     - /home/ubuntu/nato-site/html:/var/www/html
     - /home/ubuntu/nato-site/certbot/conf/:/etc/nginx/ssl/